import Navbar from "../components/Navbar"
import Head from 'next/head'
import Contact from "../components/Contact"

const contact = () => {
    return (
        <>
            <Head>
                <title>Nitin's Portfolio</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
                <script src="https://cdn.tailwindcss.com"></script>
            </Head>
            <Navbar />
            <Contact/>
        </>
    )
}

export default contact