import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Navbar from '../components/Navbar'
import Footer from '../components/Footer'
import Contact from '../components/Contact'
import Skills from '../components/Skills'
import Link from 'next/link'
import Projects from '../components/Projects'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Nitin's Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <script src="https://cdn.tailwindcss.com"></script>
      </Head>
      <Navbar/>
      <section className="text-gray-600 body-font">
        <div className="container mx-auto flex pl-20 py-0 md:flex-row flex-col items-center">
          <div className="lg:flex-grow md:w-1/2 lg:pr-24 md:pr-16 flex flex-col md:items-start md:text-left mb-16 md:mb-0 items-center text-center">
            <h1 class="title-font sm:text-4xl text-3xl mb-4 font-medium text-gray-900">Hi There,
              <br className="hidden lg:inline-block"/>I'm Nitin Garg
            </h1>
            <p className="mb-8 leading-relaxed">I am into Web development</p>
            <div className="flex justify-center">
              <Link href="/contact"><button className="inline-flex text-white bg-green-500 border-0 py-2 px-6 focus:outline-none hover:bg-green-600 rounded text-lg">Contact Me</button></Link>
              <button className="ml-4 inline-flex text-gray-700 bg-gray-100 border-0 py-2 px-6 focus:outline-none hover:bg-gray-200 rounded text-lg">Read More</button>
            </div>
            <div style={{display:'flex',height:'100px', width:'300px'}}>
              <div class="lg:w-1/4 md:w-1/2 p-4 w-full">
                <Link href="https://www.linkedin.com/in/nitin-garg-a93ba31b9">
                <img alt="" class="object-cover object-center w-full h-full block" src="linkedin.svg" style={{objectFit:'contain'}}/>
                </Link>
              </div>
              <div class="lg:w-1/4 md:w-1/2 p-4 w-full">
                <Link href="https://github.com/nitingarg2207">
                <img alt="" class="object-cover object-center w-full h-full block" src="github.svg" style={{objectFit:'contain'}}/>
                </Link>
              </div>
              <div class="lg:w-1/4 md:w-1/2 p-4 w-full">
                <Link href="https://leetcode.com/nitin2003">
                <img alt="" class="object-cover object-center w-full h-full block" src="leetcode.svg" style={{objectFit:'contain'}}/>
                </Link>
              </div> 
              <div class="lg:w-1/4 md:w-1/2 p-4 w-full">
                <Link href="https://www.hackerrank.com/nitin1960_be20">
                <img alt="" class="object-cover object-center w-full h-full block" src="hackerrank.svg" style={{objectFit:'contain'}}/>
                </Link>
              </div>    
            </div>
          </div>
          <div className="lg:max-w-lg lg:w-full md:w-1/2 w-5/6">
            <img className="object-cover object-center rounded" alt="hero" style={{width:'80%'}} src="photo2.png"/>
          </div>
        </div>
      </section>
      <br />
      <div style={{display:'flex',justifyContent:'center'}}>
        <h1 className='text-4xl font-semibold'>Skills and Technologies</h1>
      </div>
      <Skills/>
      <br />
      <div style={{display:'flex',justifyContent:'center'}}>
        <h1 className='text-4xl font-semibold'>Projects</h1>
      </div>
      <Projects/>
      <br />
      <Contact/>
      <Footer/>
      
    </div>
  )
}
